### ISSUE TITLE
Error when cross compiling: 'sys/time.h' file not found

### ISSUE THREAD

**Issue by kkettinger** [raymanfx/libv4l-rs#113]
When cross compiling my project to `armv7-unknown-linux-gnueabihf` the `v4l2-sys-mit` crate throws an error:
```
   Compiling bindgen v0.65.1
   Compiling v4l2-sys-mit v0.3.0
error: failed to run custom build command for `v4l2-sys-mit v0.3.0`

Caused by:
  process didn't exit successfully: `/workspace/target/debug/build/v4l2-sys-mit-e44acd57c82a0379/build-script-build` (exit status: 101)
  --- stderr
  /usr/include/linux/videodev2.h:60:10: fatal error: 'sys/time.h' file not found
  thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/v4l2-sys-mit-0.3.0/build.rs:10:10:
  Failed to generate bindings: ClangDiagnostic("/usr/include/linux/videodev2.h:60:10: fatal error: 'sys/time.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The `sys/time.h` file exists:
- `/usr/include/x86_64-linux-gnu/sys/time.h`
- `/usr/arm-linux-gnueabihf/include/sys/time.h`

Compiling the project directly on the target works. Any idea what could be wrong or missing?

**Comment by MarijnS95** [comment]
If anything it looks like `bindgen` isn't picking the right header here. `  /usr/include/linux/videodev2.h:60:10: fatal error: 'sys/time.h' file not found` should probably be taking the `videodev2.h` file from the sysroot at `/usr/arm-linux-gnueabihf/include/linux/videodev2.h` instead. Perhaps your cross-compliation `CFLAGS_armv7-unknown-linux-gnueabihf` (and/or `BINDGEN_EXTRA_CLANG_ARGS_armv7-unknown-linux-gnueabihf` aren't set up correctly to use the right sysroot?

**Comment by MarijnS95** [comment]
This target builds successfully for me, even without this header.

Are you perhaps building this on FreeBSD? We introduced a broken hack in #106 (and I approved it :see_no_evil:) that should have used environment variables to detect the _target_ for cross-compilation instead of the target that the build script is _compiled for_.

**Comment by kkettinger** [comment]
I'm building in a debian based vscode devcontainer (`mcr.microsoft.com/devcontainers/rust:1-1-bullseye`) under docker with windows as host system. Target is a raspberry pi.

**Comment by kkettinger** [comment]
Building it on a native debian machine works without errors.. hmm...

**Comment by kkettinger** [comment]
Updating the devcontainer to the latest version (with `clang 14`) solved the issue for me:
```diff
- "image": "mcr.microsoft.com/devcontainers/rust:1-1-bullseye",
+ "image": "mcr.microsoft.com/devcontainers/rust:latest",
```

**Comment by kkettinger** [comment]
I just had the same issue when building `v4l2-sys-mit` under Yocto with the `meta-rust` meta-layer. The problem is that bindgen/clang for the `v4l2-sys-mit` crate is missing the include path for the recipes sysroot. It then uses the hosts include path, which is wrong in the case of yocto, as yocto prepares a sysroot for the recipe with all dependencies. The path looks like this: `/build/tmp/work/cortexa7t2hf-neon-vfpv4-demo-linux-gnueabi/demo-app/1.0+git/recipe-sysroot-native/usr/include/`.

The solution (for everyone having the same issue) is setting the `CPATH` variable for clang in the recipe:
```
export CPATH = "${STAGING_DIR_TARGET}/usr/include"
```

If libclang can't be found, also set `LIBCLANG_PATH`:
```
export LIBCLANG_PATH = "${STAGING_DIR_NATIVE}${libdir}"
```

**Comment by molysgaard** [comment]
I've found this snippet to help a lot getting crates that use bindgen to compile correctly under bitbake/yocto.
```
BINDGEN_EXTRA_CLANG_ARGS = "--sysroot=${STAGING_DIR_TARGET}"
export BINDGEN_EXTRA_CLANG_ARGS
```

**Comment by kkettinger** [comment]
> I've found this snippet to help a lot getting crates that use bindgen to compile correctly under bitbake/yocto.
> 
> ```
> BINDGEN_EXTRA_CLANG_ARGS = "--sysroot=${STAGING_DIR_TARGET}"
> export BINDGEN_EXTRA_CLANG_ARGS
> ```

Great, this works perfectly. Thank you
